/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oom.mini.project;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thenullterminator
 */
public class TransactionTable extends javax.swing.JFrame {
    String accountNo = "";
    /**
     * Creates new form Transaction Table
     */
    public TransactionTable(String accountNo) {
        initComponents();
        this.accountNo = accountNo;

        loadTable();
    }

    public void loadTable() {
        Database db = Database.getInstance();
//        db.loadData();
        ArrayList<Transaction> transactionList = db.transactions;
        ArrayList<Transaction> associatedTransactionsList = new ArrayList<>();
//        System.out.println(transactionList.size());
        
        for (Transaction transaction : transactionList) {
//            System.out.println(transaction.associated + " " + this.accountNo);
            if (transaction.associated.equals(this.accountNo)) {
                associatedTransactionsList.add(transaction);
            }
        }
        
        int rows = associatedTransactionsList.size();
        String[][] data = new String[rows][5];
        
        for (int i = 0; i < rows; i++) {
            Transaction tr = associatedTransactionsList.get(i);
            String[] transaction = {tr.accountFrom,
                tr.accountTo,
                tr.debitAmount + "",
                tr.creditAmount + "",
                tr.balance + ""
            };
            data[i] = transaction;
        }
        
        String[] columnNames = {"From Account",
            "To Account",
            "Debit Amount",
            "Credit Amount",
            "Balance"
        };
        jTable1.setModel(new DefaultTableModel(data, columnNames));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TransactionTable("1").setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
